import type { Lang } from '../types';

export const weCareCopy = {
  en: {
    metaLine: 'PRODUCT STRATEGY & DESIGN · CONSULTING · 2026',
    badge: 'SHIPPED',
    heroStatement: 'WeCare is a healthcare equipment company where a single order — from a therapist request to delivery — passed through a chain of disconnected tools (Excel, SharePoint, vendor emails, invoicing, Stripe), with a person redoing every step by hand: slow, error-prone, and impossible to scale. I designed an AI-assisted platform that lets the team supervise orders instead of processing them.',
    heroBio: "I joined WeCare as an external Product Manager and Lead Engineer: I ran the discovery, framed the strategy, chose the direction, and designed and prototyped the platform. It's since been finished and shipped by WeCare's own team — company policy means I can't show the live product here, so what you'll see below are the prototypes I built.",
    s2kicker: 'THE SOLUTION',
    s2head: 'Everything manual becomes assisted.',
    s2body: 'I compared three directions — a quick no-code patch, a custom operations platform, and a fully AI-assisted version — and picked the AI-assisted one: orders are centralized first, then progressively automated, so the agent assists and a person stays in control.',
    chosenBadge: 'CHOSEN DIRECTION',
    chosenTitle: 'AI-Assisted Operations Platform',
    chosenTag: 'agent driven',
    chosenSub: 'Orders are centralized first, then progressively automated — so the team supervises operations instead of manually processing them.',
    s4kicker: 'THE PROTOTYPE',
    s4head: 'One workspace for the whole operation.',
    s4body: 'I prototyped the platform end-to-end: orders, patients and documents in one place, prices that auto-fill, and an agent that drafts orders straight from therapist emails for a human to review.',
    viewLive: 'See the live prototype',
    ctaBtn: 'See the live prototype',
    ctaNote: 'Interactive — explore the full flow',
    s5kicker: 'THE ROADMAP',
    s5head: 'Built in three phases, not one big leap.',
    s5body: 'Rather than a risky full rebuild, I sequenced the platform so the team gets value from day one and the AI layer comes online progressively. Each phase is usable on its own and de-risks the next.',
    navEyebrow: 'KEEP EXPLORING',
    backSub: 'All projects',
    backLabel: 'Back to portfolio',
    nextSub: 'Next project',
    nextLabel: 'Tardeo Argentino',
    avail: 'Open to freelance — short & long term',
  },
  es: {
    metaLine: 'PRODUCT STRATEGY & DESIGN · CONSULTORÍA · 2026',
    badge: 'ENTREGADO',
    heroStatement: 'WeCare es una empresa de equipos médicos donde un pedido — desde la solicitud del terapeuta hasta la entrega — pasaba por una cadena de herramientas desconectadas (Excel, SharePoint, emails de proveedores, facturación, Stripe), con una persona rehaciendo cada paso a mano: lento, propenso a errores e imposible de escalar. Diseñé una plataforma asistida por IA que le permite al equipo supervisar pedidos en lugar de procesarlos.',
    heroBio: 'Me sumé a WeCare como Product Manager y Lead Engineer externa: lideré el discovery, armé la estrategia, elegí la dirección, y diseñé y prototipé la plataforma. Ya está terminada y en producción, construida por el equipo propio de WeCare — por política de la empresa no puedo mostrar el producto en vivo, así que lo que vas a ver abajo son los prototipos que armé.',
    s2kicker: 'LA SOLUCIÓN',
    s2head: 'Todo lo manual se vuelve asistido.',
    s2body: 'Comparé tres direcciones — un parche rápido sin código, una plataforma de operaciones personalizada y una versión completamente asistida por IA — y elegí la asistida por IA: los pedidos se centralizan primero y luego se automatizan progresivamente, así el agente asiste y la persona mantiene el control.',
    chosenBadge: 'DIRECCIÓN ELEGIDA',
    chosenTitle: 'Plataforma de Operaciones Asistida por IA',
    chosenTag: 'dirigida por agente',
    chosenSub: 'Los pedidos se centralizan primero y luego se automatizan progresivamente — para que el equipo supervise las operaciones en lugar de procesarlas manualmente.',
    s4kicker: 'EL PROTOTIPO',
    s4head: 'Un workspace para toda la operación.',
    s4body: 'Prototipé la plataforma de punta a punta: pedidos, pacientes y documentos en un solo lugar, precios que se pre-completan y un agente que redacta pedidos desde emails de terapeutas para que un humano los revise.',
    viewLive: 'Ver el prototipo en vivo',
    ctaBtn: 'Ver el prototipo en vivo',
    ctaNote: 'Interactivo — explorá el flujo completo',
    s5kicker: 'EL ROADMAP',
    s5head: 'Construido en tres fases, no en un gran salto.',
    s5body: 'En lugar de una reconstrucción riesgosa, secuencié la plataforma para que el equipo obtenga valor desde el día uno y la capa de IA se active progresivamente. Cada fase es usable por sí sola y de-riskea la siguiente.',
    navEyebrow: 'SEGUÍ EXPLORANDO',
    backSub: 'Todos los proyectos',
    backLabel: 'Volver al portfolio',
    nextSub: 'Siguiente proyecto',
    nextLabel: 'Tardeo Argentino',
    avail: 'Disponible para freelance — corto y largo plazo',
  },
} as const;

export const skills = ['Product Strategy', 'UX Design', 'Discovery', 'Prototyping', 'AI-Assisted Ops'];

export const chosenPoints: Record<Lang, string[]> = {
  en: [
    'Agent handles repetitive operational tasks',
    'Scales without adding headcount',
    'Humans supervise the exceptions',
    'End-to-end visibility & traceability',
  ],
  es: [
    'El agente maneja tareas operativas repetitivas',
    'Escala sin agregar personal',
    'Los humanos supervisan las excepciones',
    'Visibilidad y trazabilidad de punta a punta',
  ],
};

export const phases: Record<Lang, { label: string; n: string; title: string; desc: string; bullets: string[]; cta: string }[]> = {
  en: [
    {
      label: 'PHASE 1 · CORE',
      n: '01',
      title: 'Standardize',
      desc: 'Get everything into one place with one source of truth.',
      bullets: [
        'Centralized platform for orders, patients & documents',
        'Structured product & fee tables',
        'Prices, margins & billing auto-filled',
        'Encounter, invoice & POD auto-generated',
        'Approvals routed by HCPCS code',
      ],
      cta: 'USABLE FROM DAY ONE',
    },
    {
      label: 'PHASE 2 · AUTOMATION',
      n: '02',
      title: 'Automate',
      desc: 'Let events move the order forward on their own.',
      bullets: [
        'Stripe webhook → payment detected',
        'DocuSign webhook → signature detected',
        'Shipment tracked → delivery → POD sent',
        'Order status advances automatically',
        'Vendor emails sent to the right vendor',
      ],
      cta: 'RUNS ON ITS OWN',
    },
    {
      label: 'PHASE 3 · AI',
      n: '03',
      title: 'Assist',
      desc: 'Remove the manual intake at the front of the flow.',
      bullets: [
        'Agent reads inbound therapist emails',
        'Order data extracted → draft created',
        'A human reviews and approves the draft',
        'Follow-ups & reminders automated',
        'Existing measurements detected automatically',
      ],
      cta: 'HANDS-OFF INTAKE',
    },
  ],
  es: [
    {
      label: 'FASE 1 · NÚCLEO',
      n: '01',
      title: 'Estandarizar',
      desc: 'Poner todo en un solo lugar con una única fuente de verdad.',
      bullets: [
        'Plataforma centralizada para pedidos, pacientes y documentos',
        'Tablas de productos y tarifas estructuradas',
        'Precios, márgenes y facturación pre-completados',
        'Encuentro, factura y POD auto-generados',
        'Aprobaciones enrutadas por código HCPCS',
      ],
      cta: 'USABLE DESDE EL DÍA UNO',
    },
    {
      label: 'FASE 2 · AUTOMATIZACIÓN',
      n: '02',
      title: 'Automatizar',
      desc: 'Dejar que los eventos muevan el pedido por sí solos.',
      bullets: [
        'Stripe webhook → pago detectado',
        'DocuSign webhook → firma detectada',
        'Envío rastreado → entrega → POD enviado',
        'Estado del pedido avanza automáticamente',
        'Emails enviados al proveedor correcto',
      ],
      cta: 'FUNCIONA SOLO',
    },
    {
      label: 'FASE 3 · IA',
      n: '03',
      title: 'Asistir',
      desc: 'Eliminar el ingreso manual al inicio del flujo.',
      bullets: [
        'El agente lee emails entrantes de terapeutas',
        'Datos del pedido extraídos → borrador creado',
        'Un humano revisa y aprueba el borrador',
        'Seguimientos y recordatorios automatizados',
        'Mediciones existentes detectadas automáticamente',
      ],
      cta: 'INTAKE SIN INTERVENCIÓN',
    },
  ],
};
